image: python:3.12

stages:
  - build
  - deploy

before_script:
  - apt-get update >/dev/null 2>&1
  - apt-get install -y awscli zip >/dev/null 2>&1
  - pip install aws-sam-cli >/dev/null 2>&1

# build:
#   stage: build
#   script:
#     - rm -rf .aws-sam
#     - sam build --template-file etlfs-main-stack.json

deploy:
  stage: deploy
  script:
    - source $CupawanEtlfsGroup
    - source $GarminSecrets
    - source $OwmSecrets
    - aws configure set aws_access_key_id $Aws_Access_Key
    - aws configure set aws_secret_access_key $Aws_Secret_Access_Key
    - aws configure set default.region $Aws_Default_Region
    - sam deploy --use-json --no-fail-on-empty-changeset --template-file etlfs-main-stack.json --stack-name etlfs-main-stack --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --s3-bucket "cupawandeploybucket" --s3-prefix "common/cloudformation" --region "ap-south-1" --parameter-overrides ParameterKey=SourceName,ParameterValue="$Source_Name" ParameterKey=ApplicationName,ParameterValue="$Application_Name" ParameterKey=Env,ParameterValue="$Env" ParameterKey=TelegramBotToken,ParameterValue="$Telegram_Bot_Token" ParameterKey=TelegramChatIds,ParameterValue="$Telegram_Chat_Ids" ParameterKey=MyGarminPassword,ParameterValue="$My_Garmin_Password" ParameterKey=MyEmailAddress,ParameterValue="$My_Email_Address" ParameterKey=AwsAccessKey,ParameterValue="$AWS_Access_Key" ParameterKey=AwsSecretAccessKey,ParameterValue="$AWS_Secret_Access_Key" ParameterKey=AwsS3BucketName,ParameterValue="$AWS_S3_Bucket_Name" ParameterKey=AwsS3LambdaFolderKey,ParameterValue="$AWS_S3Lambda_Folder_Key" ParameterKey=AwsS3LambdaGarminFilename,ParameterValue="$AWS_S3Lambda_Garmin_Filename" ParameterKey=MongodbConnectionString,ParameterValue="$MONGODB_Connection_String" ParameterKey=MongodbDatabase,ParameterValue="$MONGODB_Database" ParameterKey=BulletinEmailAddress,ParameterValue="$Bulletin_Email_Address" ParameterKey=BulletEmailAddressAppPassword,ParameterValue="$Bullet_Email_Address_App_Password" ParameterKey=RecEmail,ParameterValue="$Rec_Email" ParameterKey=RunningMapPath,ParameterValue="$Running_Map_Path" ParameterKey=GoogleApiKey,ParameterValue="$Google_API_Key" ParameterKey=GoogleMapsApiPath,ParameterValue="$Google_Maps_API_Path" ParameterKey=OWMApiKey,ParameterValue="$OWM_Api_Key" ParameterKey=OWMGeocodeBaseUrl,ParameterValue="$OWM_Geocode_Base_Url" ParameterKey=OWMCurrentWeatherBaseUrl,ParameterValue="$OWM_Current_Weather_Base_Url" ParameterKey=OWMGeocodeBaseUrl,ParameterValue="$OWM_Geocode_Base_Url" ParameterKey=WeatherSourceName,ParameterValue="$Weather_Source_Name" ParameterKey=StravaClientId,ParameterValue="$StravaClientId ParameterKey=StravaRedirectUri,ParameterValue="$StravaRedirectUri ParameterKey=StravaActivitiesUrl,ParameterValue="$StravaActivitiesUrl ParameterKey=StravaAuthUrl,ParameterValue="$StravaAuthUrl ParameterKey=StravaClientSecret,ParameterValue="$StravaClientSecret ParameterKey=StravaRefreshToken,ParameterValue="$StravaRefreshToken ParameterKey=StravaTokenUrl,ParameterValue="$StravaTokenUrl ParameterKey=StravaAccessToken,ParameterValue="$StravaAccessToken ParameterKey=GarminProfileImage,ParameterValue="$GarminProfileImage" ParameterKey=GarminRunHour,ParameterValue="$GarminRunHour"
  only:
    - dev
